#!/bin/bash

ls | grep -v list | grep -v regroup > list

for name in `cat list`
do 
  grep -v NaN $name > tmp 
  mv tmp $name 
done 

rm -f RP1list RP2list
for name in `cat list`
do 
  H=$(head -n 1 $name | awk '{print $2}' )
  T=$(tail -n 1 $name | awk '{print $2}' )
  if [ `echo $H | sed 's/-//g' | cut -d '.' -f 1 ` -lt 1 ]
  then 
    count=$(echo $T | grep -c - )
  else 
    count=$(echo $H | grep -c - )
  fi

  if [ $count == 1 ] 
  then 
     echo $name >> RP1list
  else
     echo $name >> RP2list
  fi
done
    
